services:
  backend:
    build:
      context: ./back
      args:
        uid: 1000
    container_name: myapp_backend
    volumes:
      - ./back:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
